import { spawnSync } from "node:child_process"
import * as fs from "node:fs"
import * as os from "node:os"
import * as path from "node:path"
import { installHarness, installOmp } from "../installer/config.js"
import { pendingBinaryRemovalPath, sweepPendingBinaryRemoval } from "./uninstall.js"
import {
  installManifestPath,
  integrationHarness,
  mergeManifestIntegrations,
  readInstallManifest,
  validateAbsoluteManifestPath,
  validateManifestOmpConfigPaths,
  validateOmpExtensionConfigPath,
  writeInstallManifest,
} from "../installer/manifest.js"
import type { InstallManifest, InstallManifestEntry, InstallManifestReadResult, PathApi } from "../installer/manifest.js"
import type { Harness, InitOptions, IntegrationResult } from "../installer/types.js"
import { VERSION } from "../version.js"
import {
  acquireUpgradeLock,
  commitWindowsUpgrade,
  handleCommittedCleanup,
  installerEnvironment,
  isCommittedCleanupRequest,
  releaseUpgradeLock,
  rollbackWindowsUpgrade,
  runTransactionalWindowsInstaller,
  snapshotInstallManifest,
} from "./windows-upgrade.js"
import type { ManifestTransaction, UpgradeLock } from "./windows-upgrade.js"

export type { InstallManifest } from "../installer/manifest.js"

const INSTALLER_URL = "https://github.com/ribbons-digital/memory-lane/releases/latest/download/install.sh"
const WINDOWS_INSTALLER_URL = "https://github.com/ribbons-digital/memory-lane/releases/latest/download/install.ps1"
// Internal self-upgrade flag: after installing a new binary, the old running process invokes the new binary with this flag so harness configs are regenerated by fresh code.
const REAPPLY_INSTALL_MANIFEST_FLAG = "--reapply-install-manifest"
const TRANSACTIONAL_WINDOWS_UPGRADE_FLAG = "--transactional-windows-upgrade"

export interface ReapplyInstallManifestResult {
  results: IntegrationResult[]
  configuredCount: number
  manifest: InstallManifest
}

export {
  acquireUpgradeLock,
  installerEnvironment,
  releaseUpgradeLock,
  snapshotInstallManifest,
} from "./windows-upgrade.js"
export type {
  ManifestTransaction,
  ProcessStartTimeInspection,
  UpgradeLock,
  UpgradeLockOptions,
} from "./windows-upgrade.js"

function runNonWindowsInstaller(scriptPath: string, installDir?: string): boolean {
  const env = installerEnvironment(process.env, installDir)
  return spawnSync("sh", [scriptPath], { stdio: "inherit", env }).status === 0
}

function downloadWithCurl(url: string, dest: string): boolean {
  const result = spawnSync("curl", ["-fsSL", url, "-o", dest], { stdio: "inherit" })
  return result.status === 0
}

function downloadWithWget(url: string, dest: string): boolean {
  const result = spawnSync("wget", ["-q", url, "-O", dest], { stdio: "inherit" })
  return result.status === 0
}

function canRun(cmd: string): boolean {
  return spawnSync(cmd, ["--version"], { stdio: "ignore" }).status === 0
}

function download(url: string, dest: string): boolean {
  if (canRun("curl")) return downloadWithCurl(url, dest)
  if (canRun("wget")) return downloadWithWget(url, dest)
  return false
}

function runInit(binaryPath: string, yes: boolean): boolean {
  const args = yes ? ["init", "--yes"] : ["init"]
  return spawnSync(binaryPath, args, { stdio: "inherit" }).status === 0
}

export function defaultInstalledBinaryPath(
  homeDir: string,
  isWindows: boolean,
  pathApi: PathApi = isWindows ? path.win32 : path,
): string {
  return isWindows
    ? pathApi.join(homeDir, "bin", "memory-lane.exe")
    : pathApi.join(homeDir, ".local", "bin", "memory-lane")
}

export function reapplyManifestWithInstalledBinary(
  binaryPath: string,
  yes: boolean,
  transactionalWindowsUpgrade = false,
  spawn: typeof spawnSync = spawnSync,
): boolean {
  const args = ["upgrade", REAPPLY_INSTALL_MANIFEST_FLAG]
  if (transactionalWindowsUpgrade) args.push(TRANSACTIONAL_WINDOWS_UPGRADE_FLAG)
  if (yes) args.push("--yes")
  return spawn(binaryPath, args, { stdio: "inherit" }).status === 0
}

const KNOWN_HARNESSES: readonly Harness[] = ["claude-code-cli", "codex-cli", "claude-desktop", "codex-desktop", "pi", "omp"]

function isKnownHarness(harness: string): harness is Harness {
  return (KNOWN_HARNESSES as readonly string[]).includes(harness)
}

function manifestError(result: Extract<InstallManifestReadResult, { status: "malformed" | "partial" }>): Error {
  return new Error(result.warnings.join(" "))
}

export function resolveInstallerDirectory(
  binaryPath: string,
  isWindows: boolean,
  hasManifest: boolean,
  pathApi: PathApi = isWindows ? path.win32 : path,
): string | undefined {
  return isWindows || hasManifest ? pathApi.dirname(binaryPath) : undefined
}

export function resolveUpgradeBinaryPath(
  result: InstallManifestReadResult,
  homeDir: string,
  isWindows: boolean,
  pathApi: PathApi = isWindows ? path.win32 : path,
): string {
  if (result.status === "missing") return defaultInstalledBinaryPath(homeDir, isWindows, pathApi)
  if (result.status === "malformed" || result.status === "partial") throw manifestError(result)

  const validated = validateAbsoluteManifestPath(result.manifest.binaryPath, "Install manifest binaryPath", pathApi)
  if (!validated.ok) throw new Error(validated.warning)
  const basename = pathApi.basename(validated.value)
  const managed = isWindows ? basename.toLowerCase() === "memory-lane.exe" : basename === "memory-lane"
  if (!managed) {
    throw new Error(`Install manifest binaryPath is not managed by the release installer: ${validated.value}`)
  }
  return validated.value
}

function validatedManifestDataDir(manifest: InstallManifest, expectedDataDir: string, isWindows: boolean): string {
  const validated = validateAbsoluteManifestPath(manifest.dataDir, "Install manifest dataDir")
  if (!validated.ok) throw new Error(validated.warning)
  const expected = path.normalize(expectedDataDir)
  const matches = isWindows
    ? validated.value.toLowerCase() === expected.toLowerCase()
    : validated.value === expected
  if (!matches) throw new Error(`Install manifest dataDir does not match the active data directory: ${validated.value}`)
  return validated.value
}

function validateTransactionalManifestIntegrations(manifest: InstallManifest): void {
  const seen = new Set<Harness>()
  for (const [index, integration] of manifest.integrations.entries()) {
    const harness = integrationHarness(integration)
    if (!harness) {
      throw new Error(`Install manifest integration ${index + 1} has no usable harness during transactional reapply.`)
    }
    if (!isKnownHarness(harness)) {
      throw new Error(`Install manifest integration ${index + 1} has unknown harness ${harness} during transactional reapply.`)
    }
    if (seen.has(harness)) {
      throw new Error(`Install manifest integration ${index + 1} has duplicate harness ${harness} during transactional reapply.`)
    }
    seen.add(harness)
  }
}

function installPreviouslyConfigured(
  options: InitOptions,
  manifest: InstallManifest,
): { results: IntegrationResult[]; replacements: InstallManifestEntry[] } {
  const results: IntegrationResult[] = []
  const replacements: InstallManifestEntry[] = []
  const seen = new Set<string>()

  for (const integration of manifest.integrations) {
    const harness = integrationHarness(integration)
    if (!harness || seen.has(harness)) continue
    seen.add(harness)
    if (!isKnownHarness(harness)) {
      const message = `Unknown harness: ${harness}`
      results.push({ harness: harness as Harness, configured: false, message })
      console.log(`  - ${harness} skipped: ${message}`)
      continue
    }

    try {
      const result = harness === "omp"
        ? (() => {
            const validated = validateOmpExtensionConfigPath(integration.configPath)
            if (!validated.ok) throw new Error(validated.warning)
            return installOmp(options, validated.value)
          })()
        : installHarness(harness, options)
      results.push(result)
      if (result.configPath) replacements.push({ harness: result.harness, configPath: result.configPath })
      console.log(`  ✓ ${harness} reconfigured`)
      if (result.message) console.log(`    ${result.message}`)
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      results.push({ harness, configured: false, message })
      console.log(`  ✗ ${harness} failed: ${message}`)
    }
  }
  return { results, replacements }
}

export function reapplyInstallManifest(
  options: InitOptions,
  manifest: InstallManifest,
  transactional = false,
): ReapplyInstallManifestResult {
  if (transactional) validateTransactionalManifestIntegrations(manifest)
  validateManifestOmpConfigPaths(manifest)
  const { results, replacements } = installPreviouslyConfigured(options, manifest)
  const configuredCount = results.filter((result) => result.configured).length
  const nextManifest: InstallManifest = {
    ...manifest,
    version: VERSION,
    installedAt: new Date().toISOString(),
    binaryPath: options.binaryPath,
    dataDir: options.dataDir,
    integrations: mergeManifestIntegrations(manifest.integrations, replacements),
  }
  if (!transactional || (configuredCount > 0 && results.every((result) => result.configured))) {
    writeInstallManifest(options.dataDir, nextManifest)
  }
  return { results, configuredCount, manifest: nextManifest }
}

export function validateReapplyManifestAvailability(
  manifest: InstallManifest | undefined,
  transactionalWindowsReapply: boolean,
): "missing" | "empty" | "ready" {
  if (!manifest) {
    if (transactionalWindowsReapply) {
      throw new Error("The required install manifest is missing during transactional Windows reapply.")
    }
    return "missing"
  }
  if (manifest.integrations.length === 0) {
    if (transactionalWindowsReapply) {
      throw new Error("The required install manifest contains no integrations during transactional Windows reapply.")
    }
    return "empty"
  }
  return "ready"
}

export async function handleUpgrade(argv: string[]): Promise<void> {
  if (isCommittedCleanupRequest(argv)) {
    await handleCommittedCleanup(argv)
    return
  }

  const yes = argv.includes("--yes")
  const reapplyOnly = argv.includes(REAPPLY_INSTALL_MANIFEST_FLAG)
  const isWindows = os.platform() === "win32"
  const transactionalWindowsReapply = isWindows && argv.includes(TRANSACTIONAL_WINDOWS_UPGRADE_FLAG)
  const url = isWindows ? WINDOWS_INSTALLER_URL : INSTALLER_URL
  const homeDir = process.env.HOME || os.homedir()
  const dataDir = path.join(homeDir, ".memory-lane")
  if (isWindows) sweepPendingBinaryRemoval(pendingBinaryRemovalPath(homeDir))
  const manifestResult = readInstallManifest(dataDir)
  const binaryPath = resolveUpgradeBinaryPath(manifestResult, homeDir, isWindows)
  const manifest = manifestResult.status === "valid" ? manifestResult.manifest : undefined
  if (manifest) {
    validatedManifestDataDir(manifest, dataDir, isWindows)
    validateManifestOmpConfigPaths(manifest)
  }

  if (reapplyOnly) {
    const manifestAvailability = validateReapplyManifestAvailability(manifest, transactionalWindowsReapply)
    if (manifestAvailability === "missing" || !manifest) {
      console.log("No previous install manifest found. Run `memory-lane init` to set up integrations.")
      return
    }
    if (manifestAvailability === "empty") {
      console.log("The install manifest is valid but contains no integrations. Run `memory-lane init` to set up integrations.")
      return
    }
    const options: InitOptions = {
      binaryPath,
      dataDir,
      projectMode: false,
      yes: true,
      homeDir,
      env: process.env,
    }
    const { results, configuredCount } = reapplyInstallManifest(options, manifest, transactionalWindowsReapply)
    const failedIntegrations = results.filter((result) => !result.configured)
    if (transactionalWindowsReapply && failedIntegrations.length > 0) {
      throw new Error(`Failed to reapply ${failedIntegrations.length} required harness configuration(s).`)
    }
    if (transactionalWindowsReapply && configuredCount === 0) {
      throw new Error("No previous harness configs were reapplied. Run `memory-lane init` to inspect integrations.")
    }
    if (configuredCount === 0) {
      console.log("No previous harness configs were reapplied. Run `memory-lane init` to inspect integrations.")
    } else {
      console.log(`Reapplied ${configuredCount} harness configuration(s).`)
    }
    return
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "memory-lane-upgrade-"))
  const scriptPath = path.join(tmpDir, isWindows ? "install.ps1" : "install.sh")
  let pendingWindowsUpgrade = false
  let installDir: string | undefined
  let manifestTransaction: ManifestTransaction | undefined
  let upgradeLock: UpgradeLock | undefined
  let preserveUpgradeLock = false
  const commitPendingWindowsUpgrade = (): void => {
    if (!pendingWindowsUpgrade) return
    if (!installDir || !upgradeLock || !commitWindowsUpgrade(installDir, upgradeLock)) {
      throw new Error("Could not finalize the Windows upgrade.")
    }
    pendingWindowsUpgrade = false
  }
  try {
    console.log("Downloading latest installer...")
    if (!download(url, scriptPath)) {
      console.error("Failed to download installer. Please upgrade manually:")
      console.error(`  ${isWindows ? "irm" : "curl -fsSL"} ${url} ${isWindows ? "| iex" : "| sh"}`)
      console.error("  memory-lane init --yes")
      process.exit(1)
    }

    console.log("Running installer...")
    installDir = resolveInstallerDirectory(binaryPath, isWindows, manifest !== undefined)
    upgradeLock = isWindows ? acquireUpgradeLock(installDir!, process.pid) : undefined
    manifestTransaction = isWindows ? snapshotInstallManifest(dataDir, process.pid) : undefined
    if (upgradeLock && manifestTransaction) upgradeLock.manifestBackupPath = manifestTransaction.backupPath
    const installed = isWindows
      ? await runTransactionalWindowsInstaller(scriptPath, installDir!, manifestTransaction!, upgradeLock!)
      : runNonWindowsInstaller(scriptPath, installDir)
    if (!installed) {
      if (isWindows && installDir && upgradeLock) {
        const restored = rollbackWindowsUpgrade(installDir, upgradeLock)
        if (!restored) {
          preserveUpgradeLock = true
          console.error("Failed to restore the previous Windows executable.")
        }
      }
      throw new Error("Installer failed. Please check the output above.")
    }
    pendingWindowsUpgrade = isWindows

    if (manifest && manifest.integrations.length > 0) {
      console.log("\nRe-configuring previously installed harnesses...")
      if (!reapplyManifestWithInstalledBinary(binaryPath, yes, isWindows)) {
        throw new Error("Reconfiguring harnesses with the newly installed binary failed.")
      }
      commitPendingWindowsUpgrade()
      console.log("Upgrade complete.")
      return
    }

    if (manifest) {
      commitPendingWindowsUpgrade()
      console.log("\nThe install manifest is valid but contains no integrations. Upgrade complete.")
      return
    }

    console.log("\nNo previous install manifest found. Running first-time setup...")
    if (!runInit(binaryPath, yes)) {
      throw new Error("Init failed after upgrade.")
    }
    commitPendingWindowsUpgrade()
    console.log("\nUpgrade complete.")
  } catch (error) {
    if (pendingWindowsUpgrade && installDir && upgradeLock) {
      if (!rollbackWindowsUpgrade(installDir, upgradeLock)) {
        preserveUpgradeLock = true
        console.error("Failed to restore the previous Windows executable.")
      }
      pendingWindowsUpgrade = false
    }
    throw error
  } finally {
    if (!preserveUpgradeLock) releaseUpgradeLock(upgradeLock)
    fs.rmSync(tmpDir, { recursive: true, force: true })
  }
}
