import type { MirrorMemoryRecord } from "./types.js"

export interface MirrorIndexFile {
  path: string
  content: string
}

const INDEX_PATHS = [
  "index.md",
  "indexes/pending.md",
  "indexes/approved.md",
  "indexes/project.md",
  "indexes/recent.md",
] as const

export function mirrorIndexFileNames(): string[] {
  return [...INDEX_PATHS]
}

function active(memories: MirrorMemoryRecord[]): MirrorMemoryRecord[] {
  return memories.filter((memory) => memory.status === "approved" || memory.status === "pending")
}

function titleFromText(text: string): string {
  const first = text.trim().split(/\r?\n/u)[0]?.replace(/^#+\s*/u, "") ?? "Memory"
  if (!first.trim()) return "Memory"
  return first.length > 80 ? `${first.slice(0, 79)}…` : first
}

function escapeLinkText(value: string): string {
  return value.replace(/([\[\]()])/gu, "\\$1")
}

function dateOnly(iso: string): string {
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return iso.slice(0, 10)
  return date.toISOString().slice(0, 10)
}

function scopeLabel(memory: MirrorMemoryRecord): string {
  return memory.scope.type === "project" ? (memory.scope.key ?? "project") : "global"
}

function frontmatter(title: string): string[] {
  return [
    "---",
    "memory_lane_mirror: true",
    "memory_lane_index: true",
    `title: ${JSON.stringify(title)}`,
    "tags:",
    "  - memory-lane",
    "  - memory-lane/index",
    "---",
    "",
    "<!-- Generated by Memory Lane. Do not edit this file directly; changes may be overwritten. -->",
    "",
  ]
}

function entry(memory: MirrorMemoryRecord): string[] {
  const title = titleFromText(memory.text)
  const kind = memory.kind ?? "memory"
  return [
    `- [${escapeLinkText(title)}](../memories/${memory.id}.md)`,
    `  - \`${memory.status}\` · \`${memory.category}\` · \`${kind}\` · \`${scopeLabel(memory)}\` · updated ${dateOnly(memory.updatedAt)}`,
  ]
}

function page(title: string, body: string[]): string {
  return [...frontmatter(title), `# ${title}`, "", ...body, ""].join("\n")
}

function listPage(title: string, memories: MirrorMemoryRecord[], empty: string): string {
  const body = memories.length ? memories.flatMap(entry) : [empty]
  return page(title, body)
}

function byUpdatedDesc(a: MirrorMemoryRecord, b: MirrorMemoryRecord): number {
  return b.updatedAt.localeCompare(a.updatedAt) || a.id.localeCompare(b.id)
}

export function renderMirrorIndexes(memories: MirrorMemoryRecord[]): MirrorIndexFile[] {
  const activeMemories = active(memories)
  const pending = activeMemories.filter((memory) => memory.status === "pending").sort(byUpdatedDesc)
  const approved = activeMemories.filter((memory) => memory.status === "approved").sort(byUpdatedDesc)
  const recent = [...activeMemories].sort(byUpdatedDesc)
  const projectMemories = activeMemories
    .filter((memory) => memory.scope.type === "project")
    .sort((a, b) => (a.scope.key ?? "").localeCompare(b.scope.key ?? "") || byUpdatedDesc(a, b))

  const groupedProject: string[] = []
  if (!projectMemories.length) {
    groupedProject.push("No project-scoped memories.")
  } else {
    let current = ""
    for (const memory of projectMemories) {
      const key = memory.scope.key ?? "project"
      if (key !== current) {
        if (groupedProject.length) groupedProject.push("")
        groupedProject.push(`## ${key}`, "")
        current = key
      }
      groupedProject.push(...entry(memory))
    }
  }

  return [
    {
      path: "index.md",
      content: page("Memory Lane", [
        "Generated index for Memory Lane's Obsidian mirror.",
        "",
        "- [Pending Memories](indexes/pending.md)",
        "- [Approved Memories](indexes/approved.md)",
        "- [Project Memories](indexes/project.md)",
        "- [Recent Memories](indexes/recent.md)",
        "",
        "JSONL remains the source of truth. These index files are generated and may be overwritten.",
      ]),
    },
    { path: "indexes/pending.md", content: listPage("Pending Memories", pending, "No pending memories.") },
    { path: "indexes/approved.md", content: listPage("Approved Memories", approved, "No approved memories.") },
    { path: "indexes/project.md", content: page("Project Memories", groupedProject) },
    { path: "indexes/recent.md", content: listPage("Recent Memories", recent, "No active memories.") },
  ]
}

export function isGeneratedMirrorIndex(content: string): boolean {
  const lines = content.split(/\r?\n/u)
  if (lines[0] !== "---") return false
  const end = lines.findIndex((line, index) => index > 0 && line.trim() === "---")
  if (end === -1) return false
  const yaml = lines.slice(1, end)
  return yaml.some((line) => /^[ \t]*memory_lane_mirror[ \t]*:[ \t]*true[ \t]*$/u.test(line))
    && yaml.some((line) => /^[ \t]*memory_lane_index[ \t]*:[ \t]*true[ \t]*$/u.test(line))
}
