import type { MirrorMemoryRecord } from "./types.js"

export function mirrorFileName(memory: Pick<MirrorMemoryRecord, "id">): string {
  return `${memory.id}.md`
}

function yamlString(value: string): string {
  return JSON.stringify(value)
}

function line(key: string, value: string | boolean | undefined): string | undefined {
  if (value === undefined) return undefined
  if (typeof value === "boolean") return `${key}: ${value}`
  return `${key}: ${yamlString(value)}`
}

function titleFromText(text: string): string {
  const first = text.trim().split(/\r?\n/u)[0]?.replace(/^#+\s*/u, "") ?? "Memory"
  if (first.length === 0) return "Memory"
  return first.length > 80 ? `${first.slice(0, 79)}…` : first
}

function tagLines(memory: MirrorMemoryRecord): string[] {
  const kind = memory.kind ?? "memory"
  return [
    "tags:",
    "  - memory-lane",
    "  - memory-lane/memory",
    `  - memory-lane/status/${memory.status}`,
    `  - memory-lane/category/${memory.category}`,
    `  - memory-lane/kind/${kind}`,
  ]
}

export function renderMemoryMarkdown(memory: MirrorMemoryRecord): string {
  const title = titleFromText(memory.text)
  const frontmatter = [
    line("memory_lane_id", memory.id),
    line("memory_lane_mirror", true),
    ...tagLines(memory),
    line("title", title),
    line("status", memory.status),
    line("category", memory.category),
    line("kind", memory.kind),
    line("scope_type", memory.scope.type),
    line("scope_key", memory.scope.key),
    line("source", memory.source),
    line("created_at", memory.createdAt),
    line("updated_at", memory.updatedAt),
    line("provenance_adapter", memory.provenance?.adapter),
    line("provenance_lifecycle_event", memory.provenance?.lifecycleEvent),
    line("provenance_tool_name", memory.provenance?.toolName),
    line("provenance_session_id", memory.provenance?.sessionId),
    line("provenance_turn_id", memory.provenance?.turnId),
  ].filter((entry): entry is string => entry !== undefined)

  return [
    "---",
    ...frontmatter,
    "---",
    "",
    "<!-- Generated by Memory Lane. Do not edit this file directly; changes may be overwritten. -->",
    "",
    `# ${title}`,
    "",
    memory.text.trim(),
    "",
  ].join("\n")
}
