import * as fs from "node:fs"
import * as path from "node:path"
import type { MirrorMemoryRecord } from "./types.js"
import { mirrorFileName, renderMemoryMarkdown } from "./markdown.js"

export interface ObsidianMirrorSettings {
  vaultPath: string
  folder?: string
}

export interface MirrorSyncResult {
  ok: boolean
  root: string
  created: number
  updated: number
  deleted: number
  warnings: string[]
}

export interface MirrorStatusResult {
  ok: boolean
  root: string
  warnings: string[]
  obsidianVault: boolean
}

function folder(settings: ObsidianMirrorSettings): string {
  return settings.folder?.trim() || "Memory Lane"
}

export function isSafeMirrorFolder(value: string): boolean {
  const trimmed = value.trim()
  return trimmed.length > 0 && !path.isAbsolute(trimmed) && !path.win32.isAbsolute(trimmed) && !trimmed.split(/[\\/]+/u).includes("..")
}

function folderWarning(settings: ObsidianMirrorSettings): string | undefined {
  if (!isSafeMirrorFolder(folder(settings))) {
    return "Mirror folder must be a relative path inside the vault."
  }
  return undefined
}

function mirrorRoot(settings: ObsidianMirrorSettings): string {
  return path.join(settings.vaultPath, folder(settings))
}

function memoriesDir(settings: ObsidianMirrorSettings): string {
  return path.join(mirrorRoot(settings), "memories")
}

function memoryPath(settings: ObsidianMirrorSettings, memory: MirrorMemoryRecord): string {
  const name = mirrorFileName(memory)
  if (path.basename(name) !== name) throw new Error(`Unsafe memory id for mirror file: ${memory.id}`)
  return path.join(memoriesDir(settings), name)
}

function isActive(memory: MirrorMemoryRecord): boolean {
  return memory.status === "approved" || memory.status === "pending"
}

function generated(content: string): boolean {
  const lines = content.split(/\r?\n/u)
  if (lines[0] !== "---") return false

  const end = lines.findIndex((line, index) => index > 0 && line.trim() === "---")
  if (end === -1) return false

  return lines.slice(1, end).some((line) => /^[ \t]*memory_lane_mirror[ \t]*:[ \t]*true[ \t]*$/u.test(line))
}

function readme(): string {
  return [
    "# Memory Lane",
    "",
    "This folder is generated by Memory Lane.",
    "",
    "- `memories/*.md` mirrors active approved and pending JSONL memory records.",
    "- JSONL remains the source of truth.",
    "- Do not edit generated memory files directly; changes may be overwritten.",
    "- Rebuild the mirror with `memory-lane obsidian sync`.",
    "",
  ].join("\n")
}

export function statusObsidianMirror(settings: ObsidianMirrorSettings): MirrorStatusResult {
  const warnings: string[] = []
  let ok = true

  const unsafeFolder = folderWarning(settings)
  if (unsafeFolder) {
    warnings.push(unsafeFolder)
    ok = false
  }

  if (!settings.vaultPath) {
    warnings.push("Vault path is required.")
    ok = false
  } else if (!fs.existsSync(settings.vaultPath)) {
    warnings.push(`Vault path does not exist: ${settings.vaultPath}`)
    ok = false
  } else if (!fs.statSync(settings.vaultPath).isDirectory()) {
    warnings.push(`Vault path is not a directory: ${settings.vaultPath}`)
    ok = false
  }

  const obsidianVault = Boolean(settings.vaultPath) && fs.existsSync(path.join(settings.vaultPath, ".obsidian"))
  if (ok && !obsidianVault) warnings.push("No .obsidian/ directory found; Memory Lane will still write Markdown here.")

  return { ok, root: mirrorRoot(settings), warnings, obsidianVault }
}

export function initObsidianMirror(settings: ObsidianMirrorSettings): MirrorSyncResult {
  const status = statusObsidianMirror(settings)
  if (!status.ok) return { ok: false, root: status.root, created: 0, updated: 0, deleted: 0, warnings: status.warnings }

  fs.mkdirSync(memoriesDir(settings), { recursive: true })
  const readmePath = path.join(mirrorRoot(settings), "README.md")
  if (!fs.existsSync(readmePath)) fs.writeFileSync(readmePath, readme(), "utf8")

  return { ok: true, root: status.root, created: 0, updated: 0, deleted: 0, warnings: status.warnings }
}

export function syncObsidianMirror(settings: ObsidianMirrorSettings, memories: MirrorMemoryRecord[], opts?: { dryRun?: boolean }): MirrorSyncResult {
  const status = statusObsidianMirror(settings)
  if (!status.ok) return { ok: false, root: status.root, created: 0, updated: 0, deleted: 0, warnings: status.warnings }

  const dryRun = opts?.dryRun === true
  const dir = memoriesDir(settings)
  if (!dryRun) {
    fs.mkdirSync(dir, { recursive: true })
    const readmePath = path.join(mirrorRoot(settings), "README.md")
    if (!fs.existsSync(readmePath)) fs.writeFileSync(readmePath, readme(), "utf8")
  }

  let created = 0
  let updated = 0
  let deleted = 0
  const active = memories.filter(isActive)
  const activeFiles = new Set(active.map(mirrorFileName))

  for (const memory of active) {
    const file = memoryPath(settings, memory)
    const next = renderMemoryMarkdown(memory)
    const exists = fs.existsSync(file)
    const current = exists ? fs.readFileSync(file, "utf8") : undefined
    if (!exists) created++
    else if (current !== next) updated++
    if (!dryRun && (!exists || current !== next)) fs.writeFileSync(file, next, "utf8")
  }

  if (fs.existsSync(dir)) {
    for (const name of fs.readdirSync(dir)) {
      if (!name.endsWith(".md") || activeFiles.has(name)) continue
      const file = path.join(dir, name)
      const stat = fs.lstatSync(file)
      if (!stat.isFile()) continue
      const content = fs.readFileSync(file, "utf8")
      if (!generated(content)) continue
      deleted++
      if (!dryRun) fs.rmSync(file)
    }
  }

  return { ok: true, root: status.root, created, updated, deleted, warnings: status.warnings }
}
