import test from "node:test"
import assert from "node:assert/strict"
import type { MemoryRecord } from "@memory-lane/core"
import { renderMemoryMarkdown, mirrorFileName } from "../src/markdown.ts"

const baseMemory: MemoryRecord = {
  id: "c6d6e4c9",
  status: "approved",
  category: "project",
  text: "This repo uses pnpm for package management.",
  scope: { type: "project", key: "/repo" },
  source: "agent-suggested",
  createdAt: "2026-05-29T00:00:00.000Z",
  updatedAt: "2026-05-29T00:00:00.000Z",
  kind: "workflow_rule",
  provenance: {
    adapter: "claude",
    lifecycleEvent: "turn_stop",
    sessionId: "session-1",
    turnId: "turn-1",
    toolName: "Bash",
  },
}

test("mirrorFileName uses stable memory id", () => {
  assert.equal(mirrorFileName(baseMemory), "c6d6e4c9.md")
})

test("renderMemoryMarkdown writes generated warning frontmatter title and body", () => {
  const markdown = renderMemoryMarkdown(baseMemory)
  assert.match(markdown, /^---\n/u)
  assert.match(markdown, /memory_lane_id: "c6d6e4c9"/u)
  assert.match(markdown, /memory_lane_mirror: true/u)
  assert.match(markdown, /status: "approved"/u)
  assert.match(markdown, /category: "project"/u)
  assert.match(markdown, /kind: "workflow_rule"/u)
  assert.match(markdown, /scope_type: "project"/u)
  assert.match(markdown, /scope_key: "\/repo"/u)
  assert.match(markdown, /source: "agent-suggested"/u)
  assert.match(markdown, /provenance_adapter: "claude"/u)
  assert.match(markdown, /provenance_lifecycle_event: "turn_stop"/u)
  assert.match(markdown, /provenance_tool_name: "Bash"/u)
  assert.match(markdown, /<!-- Generated by Memory Lane\. Do not edit this file directly; changes may be overwritten\. -->/u)
  assert.match(markdown, /# This repo uses pnpm for package management\./u)
  assert.match(markdown, /\nThis repo uses pnpm for package management\.\n$/u)
})

test("renderMemoryMarkdown escapes YAML scalar values", () => {
  const markdown = renderMemoryMarkdown({
    ...baseMemory,
    text: "Use colon: brackets [x] and quotes \"carefully\"",
    scope: { type: "project", key: "/repo:with:colon" },
  })
  assert.match(markdown, /scope_key: "\/repo:with:colon"/u)
  assert.match(markdown, /# Use colon: brackets \[x\] and quotes "carefully"/u)
})
